Pier co/chore/tdkn 297 disable message output
Talend/daikon pull request #649
Opened 2020-09-10 15:08 UTC by pierCo

**What is the problem this Pull Request is trying to solve?**

A new proposal of how to integrate the TDKN-297 feature.
 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TDKN-297
 
**Please check if the Pull Request fulfills these requirements**
- [x] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

**[ ] This Pull Request introduces a breaking change**

2020-09-10 15:29 UTC, fhuaulme requested changes

2020-09-10 15:29 UTC, fhuaulme commented on daikon-audit/README.adoc
> +To do that, the implementation of the `AbstractBackend` have to override the method `isOnHoldForFormattedMessages` in order to retuen `false` (default value is `true` - backward compatibility concide
Typo on "return"

2020-09-10 15:29 UTC, fhuaulme commented on daikon-audit/README.adoc
> +To do that, the implementation of the `AbstractBackend` have to override the method `isOnHoldForFormattedMessages` in order to retuen `false` (default value is `true` - backward compatibility concide
I would rename method from `isOnHoldForFormattedMessages` to `enableMessageFormat`

2020-09-10 15:36 UTC, anicolas commented on daikon-audit/README.adoc
> +It is possible for an `AbstractBackend` to dis  baled log messages if it doesn't need it (e.g. performance consideration).
```suggestion
It is possible for an `AbstractBackend` to disable log messages if it doesn't need it (e.g. performance consideration).
```

2020-09-11 07:43 UTC, fhuaulme approved these changes
LGTM

2020-09-11 07:44 UTC, merged