TMC-22935 Can't set schedule to task,got " Failed to save schedule." 504 error
Talend/daikon pull request #657
Opened 2020-10-01 12:26 UTC by ozatsepin

**What is the problem this Pull Request is trying to solve?**
 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2020-10-02 10:10 UTC, atelesh approved these changes

2020-10-05 10:03 UTC, fhuaulme commented
PR is waiting for more investigation on why incorrect schemes/server/port information can reach service.

2020-10-05 10:04 UTC, fhuaulme requested changes
PR is waiting for more investigation on why incorrect schemes/server/port information can reach service.

2020-10-06 14:22 UTC, fhuaulme commented
Issue was fixed at the source. Source of issue was located in Zuul header handling as documented in https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html. Fix for this issue consisted in adding `zuul.addProxyHeaders = false` to gateway configuration

2020-10-06 14:22 UTC, closed without merging