TPSVC-15325: clean MDC fields
Talend/daikon pull request #668
Opened 2020-10-27 14:00 UTC by vgagara-talend

**What is the problem this Pull Request is trying to solve?**
 https://jira.talendforge.org/browse/TPSVC-15325

**What is the chosen solution to this problem?**
clean up MDC properties after sending log 

**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2020-10-27 14:12 UTC, fhuaulme requested changes

2020-10-27 14:12 UTC, fhuaulme commented on daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/SimpleAuditLoggerBase.java
> +        try {
Wouldn't it be better to get backend's current context, store it in a "previousContext" variable, and do a `backend.resetContext(previousContext)` in the finally clause.

2020-10-27 14:42 UTC, vgagara-talend commented on daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/SimpleAuditLoggerBase.java
> +        try {
originally I thought about the option to add current context to existing one (with MDC.put(...) in setContextMap() method) and later do MDC.remove() to only properties we added here. But this will change current behavior because currently we unconditionally "wipe" existing context here https://github.com/vgagara-talend/daikon/blob/master/daikon-audit/audit-kafka/src/main/java/org/talend/logging/audit/kafka/KafkaBackend.java#L84 and maybe it is intentional. Do you propose to add new method to `AbstractBackend` something like `getContextMap()` which will return current MDC context?

2020-10-28 08:33 UTC, fhuaulme commented on daikon-audit/audit-common/src/main/java/org/talend/logging/audit/impl/SimpleAuditLoggerBase.java
> +        try {
It's better to stay consistent with KafkaBackend for the time being.

2020-10-28 08:34 UTC, fhuaulme approved these changes

2020-10-28 10:21 UTC, fhuaulme approved these changes

2020-10-28 13:19 UTC, merged