Fix TAC-14816 Update certificates for job signing on 7.1
Talend/daikon pull request #682
Opened 2020-12-03 11:04 UTC by kjwang-talend

**What is the problem this Pull Request is trying to solve?**
 For the deployed job, some job's certificate of signature will expired on Jan 2021

**What is the chosen solution to this problem?**
  For the deployed job, we will don't check the certificate expired date.
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TAC-14816
 
**Please check if the Pull Request fulfills these requirements**
- [X] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [X] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2020-12-04 10:51 UTC, coheigea requested changes

2020-12-04 10:51 UTC, coheigea commented on daikon-signature-verifier/pom.xml
> +		</dependency>
Fix formatting here.

2020-12-04 10:51 UTC, coheigea commented on daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
> +        defaultSignatureTimeStamp = cal.getTime();
What does this mean "defaultSignatureTimestamp"? And what is the relationship between 2019? Also what does it mean to set "0" for the month?

What happens when the next certificate expires?

2020-12-04 10:55 UTC, kjwang-talend commented on daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
> +        defaultSignatureTimeStamp = cal.getTime();
Actually Our office certificate will expired on Jan 2021. I set it to 2019 the reason is to take care our test case. Because the certificate using by test also expired.

2020-12-04 11:02 UTC, coheigea commented on daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
> +        defaultSignatureTimeStamp = cal.getTime();
We can't put test code though in the main source?

2020-12-04 11:25 UTC, kjwang-talend commented on daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
> +        defaultSignatureTimeStamp = cal.getTime();
Sorry, I just think any date is ok just before the certificate expired date.

2020-12-04 13:39 UTC, coheigea requested changes

2020-12-04 13:39 UTC, coheigea commented on daikon-signature-verifier/pom.xml
> +        <dependency>
Can you port the latest tests from the master branch instead so that they work on this branch as well?

2020-12-04 13:39 UTC, coheigea commented on daikon-signature-verifier/src/main/java/org/talend/daikon/signature/verify/ZipVerifier.java
> +        cal.set(Calendar.DAY_OF_MONTH, 01);
Do we need to support JAva 7 on this branch? If not it would be better to use Java 8 DateTime API.

2020-12-04 13:39 UTC, coheigea commented on daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipVerifierTest.java
> +        verifer.setCheckSignatureTimestamp(false);
If we port the latest tests + certs we probably don't need these changes. It would be good to add an explicit test for the expired case, setting checkSignatureTimestamp to false.

2020-12-07 07:50 UTC, coheigea requested changes

2020-12-07 07:50 UTC, coheigea commented on daikon-signature-verifier/pom.xml
> +        <java.version>1.8</java.version>
Are you sure that enforcing Java 8 here is OK for this branch? Can you confirm with Nicolas?

2020-12-07 07:50 UTC, coheigea commented on daikon-signature-verifier/pom.xml
> +	    </dependency>
The indentation is off here, try using spaces instead of tabs.

2020-12-07 07:51 UTC, coheigea requested changes

2020-12-07 07:51 UTC, coheigea commented on daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipVerifierWithExpiredCertTest.java
> +    private String storePass = "c1b966f70a2529d8adc13e13d293"; //$NON-NLS-1$
Please confirm this is NOT the secret password used with the default code signing/verifying keystores!

2020-12-07 08:03 UTC, kjwang-talend commented on daikon-signature-verifier/pom.xml
> +        <java.version>1.8</java.version>
Yes. Confirmed with Nicolas. Thanks

2020-12-07 08:35 UTC, kjwang-talend commented on daikon-signature-verifier/pom.xml
> +        <dependency>
Done. thanks

2020-12-07 08:36 UTC, kjwang-talend commented on daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipVerifierWithExpiredCertTest.java
> +    private String storePass = "c1b966f70a2529d8adc13e13d293"; //$NON-NLS-1$
Confirmed that they are not same. thanks

2020-12-07 08:50 UTC, kjwang-talend commented on daikon-signature-verifier/src/test/java/org/talend/daikon/signature/verify/ZipVerifierTest.java
> +        verifer.setCheckSignatureTimestamp(false);
done. thanks

2020-12-07 10:27 UTC, closed without merging