feat(TPSVC-13666): [Audit logs] Implement a prometheus counter for audit logs
Talend/daikon pull request #737
Opened 2021-05-06 10:13 UTC by fuzmah

**What is the problem this Pull Request is trying to solve?**
We don't have any metric regarding the number of audit logs generated. Thus we can't implement the coverage SLO
 
**What is the chosen solution to this problem?**
Implement a prometheus counter for audit logs which will be incremented each time an audit logs is generated 

**Link to the JIRA issue**
https://jira.talendforge.org/browse/TPSVC-13666
 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2021-05-06 11:33 UTC, fhuaulme commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
>              // Clean audit log context from PIIs
Maybe would you also be interested in `failed send audit events` count as well?

2021-05-06 12:26 UTC, fuzmah commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
>              // Clean audit log context from PIIs
Definitely. We also need to count the audit logs generated even if we didn't manage to send it

2021-05-10 11:42 UTC, fhuaulme requested changes

2021-05-10 11:42 UTC, fhuaulme commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
> +        auditLogsGeneratedCounter.increment();
Ok, but it would be better to put this in a finally statement if you want to make explicit the fact you want to increase at each call to `sendAuditLog`

2021-05-10 11:42 UTC, fhuaulme commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
> +        return Counter.builder("generated_count").description("The number of audit logs stored").register(meterRegistry);
`generated_count` is a little too generic (sorry, I should have seen this in previous review). Prefer something like `audit_log_send_count`

2021-05-10 12:27 UTC, fuzmah commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
> +        return Counter.builder("generated_count").description("The number of audit logs stored").register(meterRegistry);
IMHO `audit_log_send_count` looks more like the number of audit logs sent and doesn't include the ones which are generated but not sent due to an issue. What about `audit_log_generated_count` ?

2021-05-10 12:27 UTC, fuzmah commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/service/AuditLogSenderImpl.java
> +        auditLogsGeneratedCounter.increment();
yes sure

2021-05-10 12:58 UTC, fhuaulme commented on daikon-spring/daikon-spring-audit-logs/src/main/java/org/talend/daikon/spring/audit/logs/config/AuditLogAutoConfiguration.java
> +        return Counter.builder("generated_count").description("The number of audit logs stored").register(meterRegistry);
Ok for `audit_log_generated_count`

2021-05-10 14:29 UTC, fhuaulme approved these changes

2021-05-10 15:45 UTC, merged