TDKN-312 - Make iteration count for pbkdf2 configurable
Talend/daikon pull request #751
Opened 2021-06-03 11:30 UTC by coheigea

Currently, the iteration count for pbkdf2 is hard-coded at 65536. However, the OWASP password storage cheatsheet recommends:

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html

If FIPS-140 compliance is required, use PBKDF2 with a work factor of 310,000 or more and set with an internal hash function of HMAC-SHA-256.
We should make the iteration count configurable and recommend in Javadoc that an iteration count of 310000 is recommended.

2021-06-03 12:08 UTC, Gby56 requested changes

2021-06-03 12:08 UTC, Gby56 commented on daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
> +                KeySpec spec = new PBEKeySpec(password.toCharArray(), salt, iterations, keyLength);
Could we throw an exception here if the iterations are really too low, to have a cutoff/threshold/hard requirement in place

2021-06-03 12:08 UTC, Gby56 commented on daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
> +        return pbkDf2(password, salt, keyLength, 65536);
On top of `@Deprecated` we could add a warning log maybe ? Otherwise it's only seen at compile time

2021-06-03 13:37 UTC, coheigea commented on daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
> +                KeySpec spec = new PBEKeySpec(password.toCharArray(), salt, iterations, keyLength);
Yes good idea. Say 50000? No one is using it with less than this anyway at Talend

2021-06-03 13:38 UTC, coheigea commented on daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
> +        return pbkDf2(password, salt, keyLength, 65536);
Only the TDQ team are using it, I think instead I'd prefer to just make them migrate to the newer method once we release it. I don't really want to see warning logs in the Studio for it.

2021-06-03 15:24 UTC, Gby56 commented on daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
> +        return pbkDf2(password, salt, keyLength, 65536);
Sure then yeah, it's cleaner that way

2021-06-03 15:41 UTC, Gby56 commented on daikon-crypto/crypto-utils/src/main/java/org/talend/daikon/crypto/KeySources.java
> +                KeySpec spec = new PBEKeySpec(password.toCharArray(), salt, iterations, keyLength);
60K and we've got a deal ! 🤝

2021-06-04 10:29 UTC, Gby56 approved these changes
Looks good to me !

2021-06-04 11:20 UTC, fhuaulme approved these changes

2021-06-04 11:49 UTC, merged