TDKN-317 - Update Maven version to 3.8.2 to fix a CVE
Talend/daikon pull request #767
Opened 2021-08-31 16:25 UTC by coheigea

https://sca.analysiscenter.veracode.com/workspaces/dppFqb3/issues/vulnerabilities/82573030

maven uses insecure TLS configurations. Non-SSL repository references are allowed by default and would potentially allow for man-in-the-middle attacks.

9.1 high - CVE-2021-26291

The fix is to update to 3.8.2

2021-09-01 08:46 UTC, fhuaulme requested changes

2021-09-01 08:46 UTC, fhuaulme commented on daikon-documentation/pom.xml
> +        <maven.version>3.8.2</maven.version>
The image used to spawn K8S builder pods (in `Jenkinsfile`) needs to be updated as well with a image that provides Maven 3.8.2

2021-09-01 08:54 UTC, coheigea commented on daikon-documentation/pom.xml
> +        <maven.version>3.8.2</maven.version>
OK let's wait for TSBI. For future reference, where does this need to be updated?

2021-09-01 09:02 UTC, fhuaulme commented on daikon-documentation/pom.xml
> +        <maven.version>3.8.2</maven.version>
It needs to be updated in 2 different places:
* https://github.com/Talend/daikon/blob/3e5de6627e087e5a67ebdbf456b1cd6761b7ea14/Jenkinsfile#L40 for the build
* https://github.com/Talend/daikon/blob/3e5de6627e087e5a67ebdbf456b1cd6761b7ea14/Jenkinsfile-srcclr#L17 for the veracode static checks

2021-09-08 07:52 UTC, fhuaulme approved these changes

2021-09-08 08:14 UTC, merged