chore: replace lerna by yarn workspace and use talend-scripts
Talend/daikon pull request #791
Opened 2021-11-29 14:40 UTC by ncomont

**What is the problem this Pull Request is trying to solve?**

a lot of security alerts are raised because of lerna 

**What is the chosen solution to this problem?**
 
use yarn workspaces and talend-script

**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [x] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [x] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2021-11-29 14:48 UTC, gjou-tlnd requested changes

2021-11-29 14:48 UTC, gjou-tlnd commented on daikon-tql/daikon-tql-client/package.json
> +    "react-dom": "^16.14.0",
AFAIR we don't have react components in this lib

2021-11-29 14:49 UTC, gjou-tlnd commented on daikon-tql/daikon-tql-client/package.json
> +    "@talend/context": "^5.0.2",
is this used?

2021-11-29 22:19 UTC, ncomont commented on daikon-tql/daikon-tql-client/package.json
> +    "react-dom": "^16.14.0",
![image](https://user-images.githubusercontent.com/26482371/143951606-d21a4f4f-6071-40ff-9cab-09545e302461.png)
seems required by talend-scripts when executing tests

2021-11-29 22:23 UTC, ncomont commented on daikon-tql/daikon-tql-client/package.json
> +    "@talend/context": "^5.0.2",
oops nop, fixed thanks

2021-11-30 09:26 UTC, gjou-tlnd commented on daikon-tql/daikon-tql-client/package.json
> +    "react-dom": "^16.14.0",
I guess we need a preset for non react-lib (cc @jmfrancois)

2021-11-30 09:31 UTC, jmfrancois commented on daikon-tql/daikon-tql-client/package.json
> +    "react-dom": "^16.14.0",
test-setup require react https://github.com/Talend/ui-scripts/blob/master/packages/config-jest/test-setup.js
not react components.
It is a peerDependencies: https://github.com/Talend/ui-scripts/blob/master/packages/config-jest/package.json#L21

2021-11-30 09:31 UTC, gjou-tlnd approved these changes

2021-11-30 09:42 UTC, ncomont commented on daikon-tql/daikon-tql-client/package.json
> +    "react-dom": "^16.14.0",
thanks,
react-dom is also required (by enzyme)
![image](https://user-images.githubusercontent.com/26482371/144023072-e35e40fe-85e4-43f9-a01c-f8f9468ae4ea.png)

2021-11-30 09:44 UTC, ncomont commented on daikon-tql/daikon-tql-client/package.json
> +    "react-dom": "^16.14.0",
thanks,
react-dom is also required (by enzyme)
![image](https://user-images.githubusercontent.com/26482371/144023599-abe53a93-3596-4f08-a057-ea232c67c62e.png)

2021-11-30 09:59 UTC, jmfrancois commented on daikon-tql/README.md
> +$> yarn npm publish
you must call `yarn pre-release` before as I have seen in the package.json
The script publish do not exists in the root package.json which is private so the effect here will be to try to publish it and just fails.

2021-11-30 09:59 UTC, jmfrancois commented on daikon-tql/package.json
> +    "@changesets/cli": "^2.17.0",
do you plan to setup changset ?

2021-12-01 08:37 UTC, jmfrancois approved these changes
not different from lerna but have to note that you have to commit and push the results of changeset version which remove all changeset files, update the changelog and package.json ;)

2021-12-01 08:38 UTC, jmfrancois commented on daikon-tql/package.json
> +    "pre-release": "yarn workspaces run pre-release",
you can remove the pre-release script here you don t need it

2021-12-01 09:16 UTC, merged