chore(): common dataset schema json schema
Talend/daikon pull request #804
Opened 2021-12-28 10:35 UTC by fabballe

**What is the problem this Pull Request is trying to solve?**
 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2021-12-29 16:23 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Is DQ type force on this field",
```suggestion
      "description": "Is DQ Native type force on this field",
```

2021-12-29 16:25 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "talend.component.semanticType": {
The following fields have fully qualified names, is there any reason for this ? some compatibility requirements ?

2021-12-29 16:25 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Real label of the field",
what is a Real label ?

2022-01-03 09:57 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "talend.component.semanticType": {
This is the name defined by DPP. I have keep it like it in order to be compatible with current implementation

2022-01-03 09:58 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Real label of the field",
Real label is existing label as it is defined in a CSV/database etc. Unlike the avro `name` field It is not unique and can contains special characters

2022-01-03 10:03 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Real label of the field",
Real label sounds wierd for the description, may be just what you wrote above would be more meaningfull like
```suggestion
      "description": "Actual field or column name as defined in the original file or database",
```

2022-01-03 10:08 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Real label of the field",
You must know that in the Talend Studio there are 3 "label" for a field
name : <columnName modified / unically identifying the field like column0,column1 for not compatible names...) ==> (avro name)
ColumnName: name of the column compatible with Java code for the Code generation
DBColumnName: Original field name (can even be japanes names)

The ColumnName is not really relevant here as we don't care about Java code génération but this just to be aware of it as we will eventually have TC dataset being used in the Studio (Dizy)

2022-01-03 10:41 UTC, jad-darrous reviewed
Good job! But what about dataset statistics? In the current implementation, if the schema contains some, they will end up in `additionalProperties` field, right? In this case, it's better to have them typed, IMO.

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `dqTypeLabel` is similar to `dqType`. We remove it from the json schema definition
Seems not removed from the code.

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `description` field is added
I don't see it in DatasetFieldTypeSchema nor DatasetSchema

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `matching` fields are uniformized:
Who is responsible to do this transformation?

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +    String talendComponentLabel;
It should be in `DatasetFieldSchema`. This is where it's produced by TCK. ex: https://github.com/Talend/data-processing-runtime/blob/main/data-processing-runtime-qa/dpruntime-tests-api/tests/snowball/snowball-functional.test.ts#L16

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dq/DQTypeMatch.java
> +    static class DQTypeMatchData {
Why not public?

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "primitive type of the field",
"Avro type of the field"; it could be record, array, map..

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/test/java/org/talend/daikon/schema/DeserializerDatasetSchemaTest.java
> +    }
`System.out.println(data.getFields().get(4).getType().get(0));`

> DatasetFieldTypeSchema(type=array, dqType=null, dqTypeLabel=null, dqTypeId=null, dqNativeType=null, forced=null, nativeForced=null, fields=null, talendComponentLabel=null, talendComponentSemanticType=null, talendComponentDqType=null, talendComponentQualityAggregate=null, additionalProperties={items={type=string, dqType=Email, dqTypeLabel=Email, dqTypeId=EMAIL, isForced=false, dqNativeType=STRING, isNativeForced=false, talend.component.semanticType={total=20, matchings=[{score=70.0, total=14, name=Email, id=EMAIL}]}, talend.component.dqType={total=20, matchings=[{score=100.0, total=20, id=STRING}]}, talend.component.qualityAggregate={0=0, 1=14, total=20, -1=6}}})

All the fields are `null`, and the actual props went to `additionalProperties`

2022-01-03 10:41 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/test/resources/datasetField_valid.json
> +      "type": "string",
Not valid Avro schema.

2022-01-03 12:17 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "talend.component.dqType": {
This is confusing to have "dqType" and "talend.component.dqType"

2022-01-03 12:48 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dq/DQTypeMatch.java
> +    Set<DQTypeMatchData> matchings;
This should be a List as the matchings are ordered.

2022-01-03 12:53 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "talend.component.dqType": {
Originally, both  "talend.component.dqType" and "talend.component.semanticType" are comming from [data-quality](https://github.com/Talend/data-quality/blob/master/dataquality-statistics/src/main/java/org/talend/dataquality/statistics/type/AvroDataTypeDiscoveryAnalyzer.java#L55) and [data-quality-ee](https://github.com/Talend/data-quality-ee/blob/master/dataquality-semantic/src/main/java/org/talend/dataquality/semantic/statistics/AvroSemanticAnalyzer.java#L65), respectively. On the engine side, we kept the same naming convention. And here again, the same names are kept. I agree that it's a bit confusing, and I suggest doing the refactoring in all the layers to keep them consistent.

2022-01-03 12:56 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Real label of the field",
I'd vote for `OriginalFieldName` similar to [Schema](https://github.com/Talend/component-runtime/blob/master/component-api/src/main/java/org/talend/sdk/component/api/service/schema/Schema.java#L123) in component-runtime.

2022-01-06 13:37 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dq/DQTypeMatch.java
> +    Set<DQTypeMatchData> matchings;
fixed

2022-01-07 11:22 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +@Value
Shouldn't be `@Data` instead of `@Value`?

2022-01-07 13:42 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `dqTypeLabel` is similar to `dqType`. We remove it from the json schema definition
fix

2022-01-07 13:43 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `description` field is added
It is defined on `DatasetFieldTypeSchema.json`

```
    "description": {
      "description": "Description of the field",
      "type": "string"
    },
```

2022-01-07 13:44 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `matching` fields are uniformized:
Every project using this schema. As the based schema is generated by DPP/livy we should start by this project ?

2022-01-07 13:47 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +    String talendComponentLabel;
fix

2022-01-07 13:48 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dq/DQTypeMatch.java
> +    static class DQTypeMatchData {
fix

2022-01-07 13:49 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "primitive type of the field",
fix

2022-01-07 13:50 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/test/resources/datasetField_valid.json
> +      "type": "string",
see offline. This file is for serialization unit test. It is not planned to be a valid Avro Schema

2022-01-07 13:52 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +@Value
I only put `@Valid` in order to have immutable pojo (no setter). Pojo are created throught a builder

2022-01-07 13:56 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +@Value
But in this case, how the client can change the DQ properties? For example, setting "isForced" to true, and serializing the POJOs?

2022-01-07 13:56 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `matching` fields are uniformized:
Yes, sure.

2022-01-07 13:58 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `description` field is added
I mean, no field named `description` in the POJOs.

2022-01-07 14:12 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +@Value
`myInitalValue.toBuilder().forced(Boolean.FALSE).build()`

2022-01-07 14:13 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `description` field is added
nice catch. I add it :+1:

2022-01-07 14:15 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `description` field is added
As `originalFieldName` is under `DatasetFieldSchema` I think I will also move `description` here. WDYT ?

2022-01-07 14:26 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "talend.component.dqType": {
I make a new proposal to update this name on the dataset schema definition but indeed it should be great to align all layer if this proposal is validated

2022-01-07 14:28 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "talend.component.semanticType": {
fix

2022-01-07 14:48 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `description` field is added
Yes, no strong opinion about it :)

2022-01-07 16:26 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +@Value
```java
String originalSchema;
DatasetSchema data = objectMapper.readValue(originalSchema, DatasetSchema.class);
data.getFields().get(0).getType().get(0).setIsForced(true); // is not possible
String newSchema = objectMapper.writeValueAsString(data);
```

2022-01-10 10:49 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/test/java/org/talend/daikon/schema/DeserializerDatasetSchemaTest.java
> +        System.out.println(data.getFields().get(4).getType().get(0));
To be deleted.

2022-01-10 10:50 UTC, jad-darrous reviewed
I think that `namespace` and `logicalType` Avro properties as well as `talend.component.DATETIME` property from TCK should be available in the POJO fields instead of additionalProperties.

2022-01-10 11:03 UTC, jad-darrous reviewed
There is a `doc` property in Avro schema, maybe we can use it instead of `description` if it's enough.

2022-01-10 15:23 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +@Value
```
DatasetFieldSchema data = objectMapper.readValue(
        DatasetSchemaValidatorTest.class.getResourceAsStream("/datasetField_valid.json"), DatasetFieldSchema.class);

System.out.println("data = " + data);
List<DatasetFieldTypeSchema> types = data.getType();
types.set(0, types.get(0).toBuilder().forced(Boolean.FALSE).build());
DatasetFieldSchema newData = data.toBuilder()
        .type(types)
        .build();
System.out.println("newData = " + newData);
```
Result:
```
data = DatasetFieldSchema(name=title, type=[DatasetFieldTypeSchema(type=string, dqType=Title, dqTypeId=TITLE, dqNativeType=STRING, forced=true, nativeForced=true, fields=null, dqSemanticTypeDistribution=DQTypeMatch(total=10, matchings=[DQTypeMatchData(total=8, score=80.0, id=TITLE, name=Title), DQTypeMatchData(total=6, score=60.0, id=LANGUAGE_CODE_ISO2, name=Language Code ISO2), DQTypeMatchData(total=4, score=40.0, id=CIVILITY, name=Civility), DQTypeMatchData(total=4, score=40.0, id=COUNTRY_CODE_ISO2, name=Country Code ISO2)]), dqNativeTypeDistribution=DQTypeMatch(total=10, matchings=[DQTypeMatchData(total=10, score=100.0, id=STRING, name=null)]), dqQualityAggregate=DQQualityAggregate(total=10, valid=8, invalid=2, empty=0), additionalProperties={dqTypeLabel=Title})], originalFieldName=my real title, description=my awesome description, additionalProperties={})
newData = DatasetFieldSchema(name=title, type=[DatasetFieldTypeSchema(type=string, dqType=Title, dqTypeId=TITLE, dqNativeType=STRING, forced=false, nativeForced=true, fields=null, dqSemanticTypeDistribution=DQTypeMatch(total=10, matchings=[DQTypeMatchData(total=8, score=80.0, id=TITLE, name=Title), DQTypeMatchData(total=6, score=60.0, id=LANGUAGE_CODE_ISO2, name=Language Code ISO2), DQTypeMatchData(total=4, score=40.0, id=CIVILITY, name=Civility), DQTypeMatchData(total=4, score=40.0, id=COUNTRY_CODE_ISO2, name=Country Code ISO2)]), dqNativeTypeDistribution=DQTypeMatch(total=10, matchings=[DQTypeMatchData(total=10, score=100.0, id=STRING, name=null)]), dqQualityAggregate=DQQualityAggregate(total=10, valid=8, invalid=2, empty=0), additionalProperties={dqTypeLabel=Title})], originalFieldName=my real title, description=my awesome description, additionalProperties={})

```

2022-01-10 15:57 UTC, fabballe commented
> There is a `doc` property in Avro schema, maybe we can use it instead of `description` if it's enough.

```
doc: a JSON string providing documentation to the user of this schema (optional).
```
This field seems more link to the schema itself and not a description of our column. I think it is better to keep a specific talend field `description`

2022-01-11 14:26 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `talend.component.DATETIME` is rename `isDatetime`
Renaming `talend.component.label` and `talend.component.DATETIME` requires a change in TCK. It cannot be done on DPP side.

2022-01-17 10:24 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldSchema.java
> +    List<DatasetFieldTypeSchema> type;
We can't do this change as it need to match avro field name

2022-01-17 11:06 UTC, tlnd-jbrun commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldSchema.java
> +    List<DatasetFieldTypeSchema> type;
too bad because it would be better

2022-01-17 13:01 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `talend.component.DATETIME` is rename `isDatetime`
@jad-darrous do you know the impact of this change in TCK ?

2022-01-17 13:17 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/README.md
> +* `talend.component.DATETIME` is rename `isDatetime`
I cannot answer that. Better to ask the TDI team, there might also be some impact on the components that are using them, if any.

2022-01-17 13:19 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldSchema.java
> +
done

2022-01-17 13:19 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetSchema.java
> +
done

2022-01-17 13:19 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldTypeSchema.java
> +
done

2022-01-18 13:26 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "type": "string"
need to switch to enum

2022-01-19 13:52 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/README.md
> +* `talend.component.DATETIME` is rename `isDatetime`
Seen with TDI team: update on these keys will be part of the migration path which need to be done by each team

2022-02-03 08:43 UTC, tduperron commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetSchema.json
> +    }
I think it must be removed.

2022-02-03 11:13 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldType.java
> +public enum DatasetFieldType {
`@RequiredArgsConstructor`

2022-02-03 11:15 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/DatasetFieldType.java
> +public enum DatasetFieldType {
done

2022-02-07 15:21 UTC, jad-darrous requested changes

2022-02-07 15:21 UTC, jad-darrous commented on daikon-schema/daikon-dataset-schema/src/test/java/org/talend/daikon/schema/DeserializerSerializerTest.java
> +public class DeserializerSerializerTest {
UTs are failing with `org.json.JSONException: Duplicate key "type"`

2022-02-07 16:12 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/test/java/org/talend/daikon/schema/DeserializerSerializerTest.java
> +public class DeserializerSerializerTest {
fix

2022-02-07 16:29 UTC, jad-darrous approved these changes
LGTM!

2022-02-08 13:28 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "isNativeForced": {
What happens if both isForced (isDqTypeForced woud be better) and isNativeForced are true at the same time ?

2022-02-08 14:07 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +    "isNativeForced": {
If both are true then both native type and semantic type will be conserved if we ask for a resampling

2022-02-08 14:15 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/type/AbstractDatasetFieldTypeSchema.java
> +    @JsonProperty("isForced")
Indeed it should be great but it may impact a lot of component to do this switch. Not sure if it's worth it

2022-02-08 14:15 UTC, fabballe commented on daikon-schema/daikon-dataset-schema/src/main/resources/dataset/datasetFieldTypeSchema.json
> +      "description": "Is DQ type force on this field",
updated

2022-02-08 14:24 UTC, sgandon commented on daikon-schema/daikon-dataset-schema/src/main/java/org/talend/daikon/schema/dataset/type/AbstractDatasetFieldTypeSchema.java
> +    @JsonProperty("isForced")
ok

2022-02-08 14:28 UTC, sgandon approved these changes
LGTM

2022-02-08 16:18 UTC, merged