TPRUN-4715 CVE-2022-31692 Update spring-security-web
Talend/daikon pull request #922
Opened 2022-11-08 13:48 UTC by fzetule-t

**What is the problem this Pull Request is trying to solve?**
 CVE-2022-31692 Update spring-security-web

**What is the chosen solution to this problem?**
Directly import spring-security-web with good version
 
**Link to the JIRA issue**

 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2022-11-08 14:22 UTC, coheigea requested changes
Can you re-submit without the whitespace changes?

2022-11-08 14:53 UTC, fzetule-t commented
> Can you re-submit without the whitespace changes?

Did it, even though we should format these properly ! Why not doing it now ?

2022-11-08 14:55 UTC, coheigea commented
> > Can you re-submit without the whitespace changes?
> 
> Did it, even though we should format these properly ! Why not doing it now ?

One pull request, one concern. Whitespace changes could be done separately.

2022-11-08 15:09 UTC, coheigea approved these changes

2022-11-14 14:56 UTC, coheigea approved these changes

2022-11-14 14:59 UTC, merged