chore(TPGOV-2071): Implement get sample metadata endpoint V2
Talend/daikon pull request #969
Opened 2023-05-02 12:13 UTC by bjacobtalend

**What is the problem this Pull Request is trying to solve?**
 
**What is the chosen solution to this problem?**
 
**Link to the JIRA issue**
https://jira.talendforge.org/browse/TPGOV-2071
 
**Please check if the Pull Request fulfills these requirements**
- [ ] The PR commit message follows our [guidelines](https://github.com/Talend/daikon/blob/master/CONTRIBUTING.md)
- [ ] Tests for the changes have been added (for bug fixes / features, coverage should be over 75% in the new code)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] Related design / discussions / pages (not in JIRA), if any, are all linked or available in the Pull Request

 
**[ ] This Pull Request introduces a breaking change**

2023-05-03 08:22 UTC, fabballe requested changes

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/README.md
wrong copy paste ;)

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/pom.xml
> +        </dependency>
as daikon is moved to java 17 now. You may be able to remove lombok dep

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/DqRuleQuality.java
> +public class DqRuleQuality {
as daikon is moved to java 17 now. You may be able to replace it by a record

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/RecordField.java
> +public class RecordField {
as daikon is moved to java 17 now. You may be able to replace it by a record

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/RecordFieldQuality.java
> +public class RecordFieldQuality {
as daikon is moved to java 17 now. You may be able to replace it by a record

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/SampleMetadata.java
> +public class SampleMetadata {
as daikon is moved to java 17 now. You may be able to replace it by a record

2023-05-03 08:22 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/src/test/resources/sampleMetadata/sampleMetadataInvalid.json
From a Data Plane/Control Plane point of view you must not mix data (value) with metadata (quality) on the same schema/endpoint

2023-05-04 12:36 UTC, bjacobtalend commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/DqRuleQuality.java
> +public class DqRuleQuality {
replaced by record

2023-05-04 12:36 UTC, bjacobtalend commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/RecordField.java
> +public class RecordField {
replaced by record

2023-05-04 12:37 UTC, bjacobtalend commented on daikon-schema/daikon-dataset-sample/src/main/java/org/talend/daikon/schema/dataset/sample/metadata/SampleMetadata.java
> +public class SampleMetadata {
replaced by record

2023-05-04 12:37 UTC, bjacobtalend commented on daikon-schema/daikon-dataset-sample/src/test/resources/sampleMetadata/sampleMetadataInvalid.json
value removed

2023-05-24 07:25 UTC, fabballe requested changes
You have some tests on deserialization but no test on serialization. You should add some

2023-05-25 08:30 UTC, fabballe commented on daikon-schema/daikon-dataset-sample/src/main/resources/sample/dqRuleQuality.json
> +      "description": "rule uuid",
if it is an UUID you should add `format: "uuid"`

2023-05-25 08:43 UTC, bjacobtalend commented on daikon-schema/daikon-dataset-sample/src/main/resources/sample/dqRuleQuality.json
> +      "description": "rule uuid",
done

2023-05-25 10:05 UTC, merged